-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 11:22:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UserID` INT UNSIGNED NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password(Hash)` VARCHAR(45) NOT NULL,
  `Wallet` INT UNSIGNED NOT NULL,
  `Role` ENUM("admin", "user") NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemTypes` (
  `TypeID` INT NOT NULL,
  `ItemName` VARCHAR(45) NOT NULL,
  `ItemDescription` VARCHAR(45) NOT NULL,
  `ImgURL` VARCHAR(45) NULL,
  PRIMARY KEY (`TypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `ItemID` INT NOT NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `TypeID` INT NOT NULL,
  `Inventorycol` VARCHAR(45) NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `UserID_idx` (`UserID` ASC) VISIBLE,
  INDEX `TypeID_idx` (`TypeID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TypeID`
    FOREIGN KEY (`TypeID`)
    REFERENCES `mydb`.`ItemTypes` (`TypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marketplace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marketplace` (
  `OfferID` INT NOT NULL,
  `ItemID` INT NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  `CreationDate` DATE NOT NULL,
  PRIMARY KEY (`OfferID`),
  INDEX `ItemID_idx` (`ItemID` ASC) VISIBLE,
  CONSTRAINT `ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `mydb`.`Inventory` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction Log` (
  `TransID` INT NOT NULL,
  `TLItemID` INT NOT NULL,
  `Price` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Seller` VARCHAR(45) NULL,
  `Buyer` VARCHAR(45) NULL,
  PRIMARY KEY (`TransID`),
  INDEX `ItemID_idx` (`ItemID` ASC) VISIBLE,
  CONSTRAINT `ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `mydb`.`Inventory` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
