services:

  webserver:
    build: frontend/new-react-vite/.
    ports:
      - "80:80"

  backend:
    build: backend/.
    ports:
      - "5687:5687"
    environment:
      # Setting upp the connection info for the data base
      - DBHOST=mysql:3306
      - DBUSER=root
      - DBPASS=pswd

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      # this imports the example data tables
      - ./example/example_db.sql:/docker-entrypoint-initdb.d/example_db.sql
      # this is where the data is stored
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pswd
