services:

  webserver:
    build:
      context: frontend/new-react-vite/.
      args:
        - VITE_API_ADDRESS=ronstad.se:5687
    ports:
      - "80:80"

  backend:
    build: backend/.
    ports:
      - "5687:5687"
    environment:
      # Setting upp the connection info for the data base
      - DBHOST=mysql:3306
      - DBUSER=root
      - DBPASS=pswd
      # - CERT_FILE_PATH=/CERT/CERT
      # - CERT_KEY_FILE_PATH=/CERT/KEY
    # volumes:
    #   - ${CERT_FILE_PATH}:/CERT/CERT
    #   - ${CERT_KEY_FILE_PATH}:/CERT/KEY

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      # this imports the example data tables
      - ./example/example_db.sql:/docker-entrypoint-initdb.d/example_db.sql
      # this is where the data is stored
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pswd
